services:
    bananamanu_multiple_user.interactive_event_listener:
        class: Bananamanu\MultipleUserBundle\EventListener\InteractiveLoginListener
        arguments: [@bananamanu_multiple_user.user_matcher]
        tags:
            - { name: kernel.event_subscriber }

    bananamanu_multiple_user.user_matcher:
        class: Bananamanu\MultipleUserBundle\Service\UserMatcherService
        arguments: [@ezpublish.api.repository]

